## WeatherPy
----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
!pip install citipy

%matplotlib inline

Collecting citipy
  Using cached citipy-0.0.5.tar.gz (557 kB)
Collecting kdtree>=0.12
  Using cached kdtree-0.16-py2.py3-none-any.whl (7.7 kB)
Building wheels for collected packages: citipy
  Building wheel for citipy (setup.py): started
  Building wheel for citipy (setup.py): finished with status 'done'
  Created wheel for citipy: filename=citipy-0.0.5-py3-none-any.whl size=559704 sha256=a0dfd52fb8ee6cedfb50879578b572e025385ce83dafb9496a7d66a8a1b49943
  Stored in directory: c:\users\abhin\appdata\local\pip\cache\wheels\6d\df\5e\ad8eb9cc5ee7f4ba76865167c09f9a7edff405c669111d8353
Successfully built citipy
Installing collected packages: kdtree, citipy
Successfully installed citipy-0.0.5 kdtree-0.16

In [15]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import json
from scipy.stats import linregress

# Import API key
from api_keys import weather_api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "Output/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

## Generate Cities List

In [5]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=1500)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

595

In [5]:
#print(cities)

In [6]:
#replace space with + sign for url prep
cities = [city.replace(' ', '+') for city in cities]
#cities

### Perform API Calls
* Perform a weather check on each city using a series of successive API calls.
* Include a print log of each city as it'sbeing processed (with the city number and city name).

In [7]:
# Build query URL and request your results in Celsius
url = "http://api.openweathermap.org/data/2.5/weather?"
units = "imperial"

#actual
#query_url = f"{url}appid={weather_api_key}&q={city}&units={units}"

#full form of actual
#query_url = f"https://api.openweathermap.org/data/2.5/weather?&appid={weather_api_key}q={city}&units={units}"

#test url
query_url_test = f"{url}appid={weather_api_key}&q={cities[23]}&units={units}"
print(query_url_test)
# Get weather data (test)
city_response = requests.get(query_url_test)
city_json = city_response.json()

http://api.openweathermap.org/data/2.5/weather?appid=6f153332627c4540983d5e0900d176bd&q=manaure&units=imperial

In [8]:
#test json dumps
print(json.dumps(city_json, indent=4))

{
    "coord": {
        "lon": -72.4445,
        "lat": 11.7751
    },
    "weather": [
        {
            "id": 804,
            "main": "Clouds",
            "description": "overcast clouds",
            "icon": "04d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 86.77,
        "feels_like": 91.83,
        "temp_min": 86.77,
        "temp_max": 86.77,
        "pressure": 1006,
        "humidity": 58,
        "sea_level": 1006,
        "grnd_level": 1006
    },
    "visibility": 10000,
    "wind": {
        "speed": 15.73,
        "deg": 82,
        "gust": 19.44
    },
    "clouds": {
        "all": 99
    },
    "dt": 1618519882,
    "sys": {
        "country": "CO",
        "sunrise": 1618483063,
        "sunset": 1618527679
    },
    "timezone": -18000,
    "id": 3675504,
    "name": "Manaure",
    "cod": 200
}

In [9]:
#testing where needed data is in the json file
print(city_json["coord"])
print(city_json["coord"]["lon"])
print(city_json["coord"]["lat"])
print(city_json["main"]["temp_max"])
print(city_json["main"]["humidity"])
print(city_json["clouds"]["all"])
print(city_json["wind"]["speed"])
print(city_json["sys"]["country"])
print(city_json["dt"])
print(city_json["name"])

{'lon': -72.4445, 'lat': 11.7751}
-72.4445
11.7751
86.77
58
99
15.73
CO
1618519882
Manaure

In [10]:
count = 1
groupcount = 1
#remaking cities list in case a city can't be found in api
city_name = []
lon = []
lat = []
max_temp = []
humidity = []
cloudiness = []
wind_speed = []
country = []
date = []
linebreak = "---------------------------------------------------------------------------"

print("Beginning Data Retrieval")
print(linebreak)

for city in cities:
    
    query_url = f"{url}appid={weather_api_key}&q={city}&units={units}"
#    print(query_url)
    
    try:
        city_response = requests.get(query_url)
        city_json = city_response.json()
        city_name.append(city_json["name"])
        lon.append(city_json["coord"]["lon"])
        lat.append(city_json["coord"]["lat"])
        max_temp.append(city_json["main"]["temp_max"])
        humidity.append(city_json["main"]["humidity"])
        cloudiness.append(city_json["clouds"]["all"])
        wind_speed.append(city_json["wind"]["speed"])
        country.append(city_json["sys"]["country"])
        date.append(city_json["dt"])
        
        print(f"Processing Record {count} of Set {groupcount} | {city}")
        count += 1
        
    except:
        print("City not found. Skipping ...")
        pass
        
    if count > 50:
            groupcount += 1
            count = 1
            
print(linebreak)
print("Data Retrieval Complete")
print(linebreak)

Beginning Data Retrieval
---------------------------------------------------------------------------
City not found. Skipping ...
Processing Record 1 of Set 1 | mataundh
Processing Record 2 of Set 1 | port+blair
Processing Record 3 of Set 1 | gizo
City not found. Skipping ...
Processing Record 4 of Set 1 | killybegs
Processing Record 5 of Set 1 | agua+dulce
Processing Record 6 of Set 1 | otjiwarongo
Processing Record 7 of Set 1 | tikamgarh
Processing Record 8 of Set 1 | mareeba
Processing Record 9 of Set 1 | san+quintin
Processing Record 10 of Set 1 | anadyr
Processing Record 11 of Set 1 | ewa+beach
Processing Record 12 of Set 1 | ibra
City not found. Skipping ...
Processing Record 13 of Set 1 | punta+arenas
Processing Record 14 of Set 1 | ribeirao+das+neves
Processing Record 15 of Set 1 | praia+da+vitoria
Processing Record 16 of Set 1 | new+norfolk
Processing Record 17 of Set 1 | bluff
Processing Record 18 of Set 1 | narsaq
Processing Record 19 of Set 1 | tuktoyaktuk
Processing Record 20 of Set 1 | shingu
Processing Record 21 of Set 1 | manaure
Processing Record 22 of Set 1 | mataura
Processing Record 23 of Set 1 | yulara
Processing Record 24 of Set 1 | kununurra
Processing Record 25 of Set 1 | ushuaia
Processing Record 26 of Set 1 | atuona
Processing Record 27 of Set 1 | busselton
Processing Record 28 of Set 1 | hobart
Processing Record 29 of Set 1 | butaritari
Processing Record 30 of Set 1 | barrow
Processing Record 31 of Set 1 | hermanus
Processing Record 32 of Set 1 | walvis+bay
Processing Record 33 of Set 1 | port+elizabeth
Processing Record 34 of Set 1 | yellowknife
Processing Record 35 of Set 1 | acarau
Processing Record 36 of Set 1 | niltepec
Processing Record 37 of Set 1 | faanui
Processing Record 38 of Set 1 | halifax
Processing Record 39 of Set 1 | mawlaik
Processing Record 40 of Set 1 | ingham
Processing Record 41 of Set 1 | vaini
Processing Record 42 of Set 1 | kaitangata
Processing Record 43 of Set 1 | arraial+do+cabo
Processing Record 44 of Set 1 | nouadhibou
Processing Record 45 of Set 1 | kapaa
Processing Record 46 of Set 1 | longyearbyen
Processing Record 47 of Set 1 | hualmay
Processing Record 48 of Set 1 | pushkino
Processing Record 49 of Set 1 | rikitea
Processing Record 50 of Set 1 | melilla
Processing Record 1 of Set 2 | georgetown
Processing Record 2 of Set 2 | dingle
Processing Record 3 of Set 2 | tiksi
Processing Record 4 of Set 2 | batemans+bay
Processing Record 5 of Set 2 | provideniya
Processing Record 6 of Set 2 | chara
Processing Record 7 of Set 2 | dunaharaszti
Processing Record 8 of Set 2 | lavrentiya
Processing Record 9 of Set 2 | isangel
Processing Record 10 of Set 2 | luderitz
Processing Record 11 of Set 2 | smolenka
Processing Record 12 of Set 2 | inhambane
Processing Record 13 of Set 2 | tasiilaq
Processing Record 14 of Set 2 | hofn
City not found. Skipping ...
Processing Record 15 of Set 2 | yaguajay
Processing Record 16 of Set 2 | xining
City not found. Skipping ...
Processing Record 17 of Set 2 | dikson
Processing Record 18 of Set 2 | acajutla
Processing Record 19 of Set 2 | chokurdakh
Processing Record 20 of Set 2 | upernavik
Processing Record 21 of Set 2 | haines+junction
City not found. Skipping ...
Processing Record 22 of Set 2 | shar
Processing Record 23 of Set 2 | east+london
Processing Record 24 of Set 2 | naze
Processing Record 25 of Set 2 | guerrero+negro
Processing Record 26 of Set 2 | puerto+ayora
Processing Record 27 of Set 2 | devarkonda
Processing Record 28 of Set 2 | andapa
Processing Record 29 of Set 2 | cape+town
City not found. Skipping ...
Processing Record 30 of Set 2 | srednekolymsk
Processing Record 31 of Set 2 | khatanga
City not found. Skipping ...
City not found. Skipping ...
Processing Record 32 of Set 2 | stykkisholmur
Processing Record 33 of Set 2 | banjar
Processing Record 34 of Set 2 | port+alfred
Processing Record 35 of Set 2 | brownsville
Processing Record 36 of Set 2 | bredasdorp
Processing Record 37 of Set 2 | riberalta
Processing Record 38 of Set 2 | hithadhoo
City not found. Skipping ...
Processing Record 39 of Set 2 | padang
Processing Record 40 of Set 2 | namibe
Processing Record 41 of Set 2 | jamestown
City not found. Skipping ...
Processing Record 42 of Set 2 | nelson
Processing Record 43 of Set 2 | chapais
Processing Record 44 of Set 2 | saint-georges
Processing Record 45 of Set 2 | veraval
Processing Record 46 of Set 2 | brigantine
Processing Record 47 of Set 2 | albany
City not found. Skipping ...
Processing Record 48 of Set 2 | camacupa
Processing Record 49 of Set 2 | auki
Processing Record 50 of Set 2 | ambanja
City not found. Skipping ...
Processing Record 1 of Set 3 | praia
Processing Record 2 of Set 3 | mayor+pablo+lagerenza
City not found. Skipping ...
Processing Record 3 of Set 3 | cidreira
Processing Record 4 of Set 3 | wiarton
City not found. Skipping ...
Processing Record 5 of Set 3 | college
Processing Record 6 of Set 3 | yining
Processing Record 7 of Set 3 | camacha
Processing Record 8 of Set 3 | amahai
Processing Record 9 of Set 3 | chuy
Processing Record 10 of Set 3 | lorengau
Processing Record 11 of Set 3 | norman+wells
Processing Record 12 of Set 3 | aykhal
Processing Record 13 of Set 3 | qaanaaq
Processing Record 14 of Set 3 | deputatskiy
City not found. Skipping ...
Processing Record 15 of Set 3 | fairbanks
Processing Record 16 of Set 3 | umm+kaddadah
Processing Record 17 of Set 3 | griffith
Processing Record 18 of Set 3 | funadhoo
Processing Record 19 of Set 3 | jumla
Processing Record 20 of Set 3 | sokna
Processing Record 21 of Set 3 | parrita
Processing Record 22 of Set 3 | kahului
Processing Record 23 of Set 3 | cabo+san+lucas
City not found. Skipping ...
Processing Record 24 of Set 3 | dayong
City not found. Skipping ...
Processing Record 25 of Set 3 | vardo
Processing Record 26 of Set 3 | koroni
Processing Record 27 of Set 3 | kruisfontein
Processing Record 28 of Set 3 | kavieng
Processing Record 29 of Set 3 | selkirk
Processing Record 30 of Set 3 | mar+del+plata
Processing Record 31 of Set 3 | pochutla
Processing Record 32 of Set 3 | upington
Processing Record 33 of Set 3 | avarua
Processing Record 34 of Set 3 | harper
Processing Record 35 of Set 3 | los+llanos+de+aridane
Processing Record 36 of Set 3 | korla
Processing Record 37 of Set 3 | santa+ana
Processing Record 38 of Set 3 | palu
Processing Record 39 of Set 3 | kaniama
Processing Record 40 of Set 3 | castro
Processing Record 41 of Set 3 | makueni
Processing Record 42 of Set 3 | marsh+harbour
Processing Record 43 of Set 3 | rexburg
City not found. Skipping ...
Processing Record 44 of Set 3 | saldanha
Processing Record 45 of Set 3 | clyde+river
Processing Record 46 of Set 3 | turukhansk
Processing Record 47 of Set 3 | nikolskoye
Processing Record 48 of Set 3 | gazanjyk
Processing Record 49 of Set 3 | banihal
Processing Record 50 of Set 3 | lewisporte
Processing Record 1 of Set 4 | tigil
Processing Record 2 of Set 4 | santa+rosa+de+lima
City not found. Skipping ...
Processing Record 3 of Set 4 | bethel
City not found. Skipping ...
Processing Record 4 of Set 4 | salisbury
Processing Record 5 of Set 4 | kutum
Processing Record 6 of Set 4 | tiznit
Processing Record 7 of Set 4 | cherskiy
Processing Record 8 of Set 4 | hay+river
Processing Record 9 of Set 4 | itarema
Processing Record 10 of Set 4 | tautira
Processing Record 11 of Set 4 | tuatapere
Processing Record 12 of Set 4 | esperance
Processing Record 13 of Set 4 | talara
Processing Record 14 of Set 4 | mehamn
Processing Record 15 of Set 4 | ust-nera
Processing Record 16 of Set 4 | teguise
Processing Record 17 of Set 4 | carnarvon
Processing Record 18 of Set 4 | constitucion
Processing Record 19 of Set 4 | kupang
Processing Record 20 of Set 4 | niwari
Processing Record 21 of Set 4 | bambous+virieux
Processing Record 22 of Set 4 | santa+cruz+del+sur
Processing Record 23 of Set 4 | aleksandrov+gay
Processing Record 24 of Set 4 | tura
Processing Record 25 of Set 4 | dali
City not found. Skipping ...
Processing Record 26 of Set 4 | altus
City not found. Skipping ...
Processing Record 27 of Set 4 | teya
City not found. Skipping ...
Processing Record 28 of Set 4 | porto+novo
Processing Record 29 of Set 4 | severo-kurilsk
Processing Record 30 of Set 4 | poshekhonye

Processing Record 31 of Set 4 | baykit
Processing Record 32 of Set 4 | saint+george
Processing Record 33 of Set 4 | san+patricio
Processing Record 34 of Set 4 | leningradskiy
Processing Record 35 of Set 4 | ranong
Processing Record 36 of Set 4 | santa+maria+da+vitoria
Processing Record 37 of Set 4 | paamiut
Processing Record 38 of Set 4 | mount+gambier
Processing Record 39 of Set 4 | avenal
Processing Record 40 of Set 4 | mykhaylivka
City not found. Skipping ...
Processing Record 41 of Set 4 | santa+catarina+de+tepehuanes
Processing Record 42 of Set 4 | brae
Processing Record 43 of Set 4 | plymouth
Processing Record 44 of Set 4 | alegrete
Processing Record 45 of Set 4 | oussouye
Processing Record 46 of Set 4 | sakti
Processing Record 47 of Set 4 | torbay
Processing Record 48 of Set 4 | saint-philippe
Processing Record 49 of Set 4 | moctezuma
Processing Record 50 of Set 4 | hilo
Processing Record 1 of Set 5 | caravelas
Processing Record 2 of Set 5 | hirapur
Processing Record 3 of Set 5 | nabire
Processing Record 4 of Set 5 | lagoa
Processing Record 5 of Set 5 | rudnogorsk
Processing Record 6 of Set 5 | phan+thiet
Processing Record 7 of Set 5 | hamilton
Processing Record 8 of Set 5 | tahe
Processing Record 9 of Set 5 | acapulco
Processing Record 10 of Set 5 | paragominas
Processing Record 11 of Set 5 | airai
Processing Record 12 of Set 5 | genova
Processing Record 13 of Set 5 | bilibino
Processing Record 14 of Set 5 | vostok
Processing Record 15 of Set 5 | bengkulu
Processing Record 16 of Set 5 | high+level
Processing Record 17 of Set 5 | kongolo
City not found. Skipping ...
City not found. Skipping ...
Processing Record 18 of Set 5 | bandarbeyla
Processing Record 19 of Set 5 | tenosique
Processing Record 20 of Set 5 | kandi
City not found. Skipping ...
Processing Record 21 of Set 5 | pisco
Processing Record 22 of Set 5 | bereda
Processing Record 23 of Set 5 | kidal
Processing Record 24 of Set 5 | kodiak
Processing Record 25 of Set 5 | ribeira+grande
Processing Record 26 of Set 5 | bedford
Processing Record 27 of Set 5 | markala
Processing Record 28 of Set 5 | bambanglipuro
Processing Record 29 of Set 5 | cayenne
Processing Record 30 of Set 5 | goundam
Processing Record 31 of Set 5 | klaksvik
Processing Record 32 of Set 5 | krasnoselkup
Processing Record 33 of Set 5 | zhaozhou
Processing Record 34 of Set 5 | cairns
Processing Record 35 of Set 5 | shakawe
Processing Record 36 of Set 5 | zacualpan
Processing Record 37 of Set 5 | stephenville
Processing Record 38 of Set 5 | mirnyy
Processing Record 39 of Set 5 | asfi
Processing Record 40 of Set 5 | humberto+de+campos
Processing Record 41 of Set 5 | aquiles+serdan
Processing Record 42 of Set 5 | kudahuvadhoo
Processing Record 43 of Set 5 | souillac
Processing Record 44 of Set 5 | darnah
Processing Record 45 of Set 5 | karratha
Processing Record 46 of Set 5 | kyra
City not found. Skipping ...
Processing Record 47 of Set 5 | buritis
Processing Record 48 of Set 5 | mahanoro
Processing Record 49 of Set 5 | doha
Processing Record 50 of Set 5 | samarai
Processing Record 1 of Set 6 | wajima
Processing Record 2 of Set 6 | komsomolskiy
Processing Record 3 of Set 6 | binika
Processing Record 4 of Set 6 | xiamen
Processing Record 5 of Set 6 | warrnambool
Processing Record 6 of Set 6 | gawler
Processing Record 7 of Set 6 | litovko
Processing Record 8 of Set 6 | liuhe
Processing Record 9 of Set 6 | roebourne
Processing Record 10 of Set 6 | takoradi
Processing Record 11 of Set 6 | guozhen
Processing Record 12 of Set 6 | abbeville
Processing Record 13 of Set 6 | batagay-alyta
Processing Record 14 of Set 6 | saint-pierre
Processing Record 15 of Set 6 | namatanai
Processing Record 16 of Set 6 | thompson
Processing Record 17 of Set 6 | san+juan
Processing Record 18 of Set 6 | ust-omchug
Processing Record 19 of Set 6 | kemijarvi
City not found. Skipping ...
Processing Record 20 of Set 6 | adrar
Processing Record 21 of Set 6 | keetmanshoop
Processing Record 22 of Set 6 | iqaluit
Processing Record 23 of Set 6 | salinopolis
Processing Record 24 of Set 6 | atar
Processing Record 25 of Set 6 | bousso
Processing Record 26 of Set 6 | dagua
City not found. Skipping ...
Processing Record 27 of Set 6 | vestmannaeyjar
Processing Record 28 of Set 6 | valentin+gomez+farias
Processing Record 29 of Set 6 | rawson
Processing Record 30 of Set 6 | palanas
Processing Record 31 of Set 6 | puri
Processing Record 32 of Set 6 | roma
Processing Record 33 of Set 6 | gwanda
Processing Record 34 of Set 6 | formosa
Processing Record 35 of Set 6 | port+augusta
Processing Record 36 of Set 6 | olinda
Processing Record 37 of Set 6 | kalmar
Processing Record 38 of Set 6 | evensk
Processing Record 39 of Set 6 | muriwai+beach
Processing Record 40 of Set 6 | coquimbo
Processing Record 41 of Set 6 | kisanga
Processing Record 42 of Set 6 | san+lorenzo
Processing Record 43 of Set 6 | valparaiso
Processing Record 44 of Set 6 | payson
Processing Record 45 of Set 6 | kulhudhuffushi
Processing Record 46 of Set 6 | gunnedah
Processing Record 47 of Set 6 | cap+malheureux
Processing Record 48 of Set 6 | angoche
Processing Record 49 of Set 6 | maragogi
Processing Record 50 of Set 6 | martapura
Processing Record 1 of Set 7 | saint+anthony
Processing Record 2 of Set 7 | menongue
Processing Record 3 of Set 7 | lasa
Processing Record 4 of Set 7 | vung+tau
City not found. Skipping ...
Processing Record 5 of Set 7 | juneau
Processing Record 6 of Set 7 | qeshm
Processing Record 7 of Set 7 | nassau
Processing Record 8 of Set 7 | penzance
Processing Record 9 of Set 7 | taksimo
Processing Record 10 of Set 7 | somerville
Processing Record 11 of Set 7 | mangai
Processing Record 12 of Set 7 | plouzane
Processing Record 13 of Set 7 | waddan
Processing Record 14 of Set 7 | orange
Processing Record 15 of Set 7 | manuk+mangkaw
Processing Record 16 of Set 7 | mugur-aksy
Processing Record 17 of Set 7 | saskylakh
Processing Record 18 of Set 7 | ponta+do+sol
Processing Record 19 of Set 7 | bermeo
Processing Record 20 of Set 7 | jalu
Processing Record 21 of Set 7 | pringsewu
City not found. Skipping ...
Processing Record 22 of Set 7 | bathsheba
Processing Record 23 of Set 7 | kristiinankaupunki
Processing Record 24 of Set 7 | hammerfest
Processing Record 25 of Set 7 | lebu
Processing Record 26 of Set 7 | baiyin
Processing Record 27 of Set 7 | namtsy
Processing Record 28 of Set 7 | disna
Processing Record 29 of Set 7 | imbituba
Processing Record 30 of Set 7 | zhigansk
Processing Record 31 of Set 7 | touros
Processing Record 32 of Set 7 | bacabal
Processing Record 33 of Set 7 | pentecoste
City not found. Skipping ...
Processing Record 34 of Set 7 | zeya
Processing Record 35 of Set 7 | pevek
Processing Record 36 of Set 7 | rodniki
Processing Record 37 of Set 7 | sur
Processing Record 38 of Set 7 | conde
Processing Record 39 of Set 7 | neustadt
Processing Record 40 of Set 7 | santo+domingo
Processing Record 41 of Set 7 | furano
Processing Record 42 of Set 7 | lompoc
Processing Record 43 of Set 7 | vila+velha
Processing Record 44 of Set 7 | kavaratti
Processing Record 45 of Set 7 | rimini
Processing Record 46 of Set 7 | mount+isa
City not found. Skipping ...
Processing Record 47 of Set 7 | gatton
Processing Record 48 of Set 7 | santa+luzia
Processing Record 49 of Set 7 | mujiayingzi
Processing Record 50 of Set 7 | kokopo
Processing Record 1 of Set 8 | am+timan
Processing Record 2 of Set 8 | necochea
Processing Record 3 of Set 8 | dudinka
Processing Record 4 of Set 8 | matinhos
Processing Record 5 of Set 8 | cootamundra
Processing Record 6 of Set 8 | the+pas
Processing Record 7 of Set 8 | mercedes
Processing Record 8 of Set 8 | aklavik
Processing Record 9 of Set 8 | kysyl-syr
Processing Record 10 of Set 8 | iralaya
Processing Record 11 of Set 8 | honiara
Processing Record 12 of Set 8 | beringovskiy
Processing Record 13 of Set 8 | ust-kuyga
Processing Record 14 of Set 8 | parkes
City not found. Skipping ...
Processing Record 15 of Set 8 | skjervoy
Processing Record 16 of Set 8 | san+cristobal
Processing Record 17 of Set 8 | victoria
Processing Record 18 of Set 8 | broken+hill
Processing Record 19 of Set 8 | dickson
Processing Record 20 of Set 8 | cassilandia
City not found. Skipping ...

Processing Record 21 of Set 8 | paita
Processing Record 22 of Set 8 | virginia+beach
Processing Record 23 of Set 8 | piacabucu
Processing Record 24 of Set 8 | asau
Processing Record 25 of Set 8 | xingyi
City not found. Skipping ...
Processing Record 26 of Set 8 | alihe
Processing Record 27 of Set 8 | aketi
Processing Record 28 of Set 8 | avera
Processing Record 29 of Set 8 | ahipara
Processing Record 30 of Set 8 | mahebourg
Processing Record 31 of Set 8 | hovd
Processing Record 32 of Set 8 | bay+roberts
Processing Record 33 of Set 8 | ilulissat
Processing Record 34 of Set 8 | sarh
Processing Record 35 of Set 8 | izumo
Processing Record 36 of Set 8 | pangnirtung
Processing Record 37 of Set 8 | trani
Processing Record 38 of Set 8 | salalah
Processing Record 39 of Set 8 | leh
Processing Record 40 of Set 8 | jaru
Processing Record 41 of Set 8 | jacmel
City not found. Skipping ...
Processing Record 42 of Set 8 | richards+bay
Processing Record 43 of Set 8 | rawah
Processing Record 44 of Set 8 | axim
Processing Record 45 of Set 8 | kaitong
Processing Record 46 of Set 8 | wicklow
Processing Record 47 of Set 8 | ponta+delgada
Processing Record 48 of Set 8 | nenjiang
City not found. Skipping ...
Processing Record 49 of Set 8 | katsina
Processing Record 50 of Set 8 | saint-francois
Processing Record 1 of Set 9 | kristiansund
Processing Record 2 of Set 9 | fortuna
Processing Record 3 of Set 9 | krasnyy+chikoy
Processing Record 4 of Set 9 | araouane
Processing Record 5 of Set 9 | dong+hoi
Processing Record 6 of Set 9 | maldonado
Processing Record 7 of Set 9 | jardim
Processing Record 8 of Set 9 | boa+vista
Processing Record 9 of Set 9 | lata
Processing Record 10 of Set 9 | shaowu
Processing Record 11 of Set 9 | alofi
Processing Record 12 of Set 9 | moshi
Processing Record 13 of Set 9 | nuevo+progreso
Processing Record 14 of Set 9 | geraldton
City not found. Skipping ...
Processing Record 15 of Set 9 | wattegama
Processing Record 16 of Set 9 | petropavlovsk-kamchatskiy
Processing Record 17 of Set 9 | port+hedland
Processing Record 18 of Set 9 | talcahuano
Processing Record 19 of Set 9 | hobyo
Processing Record 20 of Set 9 | vao
Processing Record 21 of Set 9 | cabedelo
City not found. Skipping ...
Processing Record 22 of Set 9 | oktyabrskiy
Processing Record 23 of Set 9 | kirakira
Processing Record 24 of Set 9 | broome
Processing Record 25 of Set 9 | baruun-urt
Processing Record 26 of Set 9 | ulladulla
Processing Record 27 of Set 9 | balezino
Processing Record 28 of Set 9 | salamanca
Processing Record 29 of Set 9 | itororo
Processing Record 30 of Set 9 | qaqortoq
Processing Record 31 of Set 9 | porto+santo
Processing Record 32 of Set 9 | beloha
Processing Record 33 of Set 9 | omboue
Processing Record 34 of Set 9 | ostrovnoy
Processing Record 35 of Set 9 | saint-augustin
Processing Record 36 of Set 9 | dwarka
Processing Record 37 of Set 9 | talnakh
Processing Record 38 of Set 9 | lingyuan
Processing Record 39 of Set 9 | thaton
Processing Record 40 of Set 9 | vestmanna
Processing Record 41 of Set 9 | carballo
Processing Record 42 of Set 9 | sitka
Processing Record 43 of Set 9 | kamen-rybolov
Processing Record 44 of Set 9 | juayua
Processing Record 45 of Set 9 | mackenzie
City not found. Skipping ...
Processing Record 46 of Set 9 | hanumangarh
Processing Record 47 of Set 9 | berlevag
Processing Record 48 of Set 9 | shestakovo
Processing Record 49 of Set 9 | polkowice
Processing Record 50 of Set 9 | codrington
Processing Record 1 of Set 10 | cienfuegos
Processing Record 2 of Set 10 | copiapo
Processing Record 3 of Set 10 | horsham
Processing Record 4 of Set 10 | arica
Processing Record 5 of Set 10 | havoysund
Processing Record 6 of Set 10 | show+low
Processing Record 7 of Set 10 | road+town
Processing Record 8 of Set 10 | kuusamo
Processing Record 9 of Set 10 | bolama
Processing Record 10 of Set 10 | esso
Processing Record 11 of Set 10 | dabakala
Processing Record 12 of Set 10 | coihaique
Processing Record 13 of Set 10 | huilong
Processing Record 14 of Set 10 | egvekinot
Processing Record 15 of Set 10 | sehwan
Processing Record 16 of Set 10 | affery
Processing Record 17 of Set 10 | caconda
Processing Record 18 of Set 10 | kharp
Processing Record 19 of Set 10 | malakal
Processing Record 20 of Set 10 | hailar
Processing Record 21 of Set 10 | posse
Processing Record 22 of Set 10 | nishihara
Processing Record 23 of Set 10 | grindavik
Processing Record 24 of Set 10 | callaway
Processing Record 25 of Set 10 | cervo
Processing Record 26 of Set 10 | sao+filipe
Processing Record 27 of Set 10 | paraiso
Processing Record 28 of Set 10 | tarakan
Processing Record 29 of Set 10 | atikokan
Processing Record 30 of Set 10 | gasa
Processing Record 31 of Set 10 | san+vicente
Processing Record 32 of Set 10 | ust-tsilma
Processing Record 33 of Set 10 | gravdal
Processing Record 34 of Set 10 | tortoli
Processing Record 35 of Set 10 | arman
City not found. Skipping ...
Processing Record 36 of Set 10 | bilma
City not found. Skipping ...
Processing Record 37 of Set 10 | hambantota
Processing Record 38 of Set 10 | ayan
Processing Record 39 of Set 10 | yarim
Processing Record 40 of Set 10 | jiuquan
Processing Record 41 of Set 10 | pithiviers
Processing Record 42 of Set 10 | buraydah
Processing Record 43 of Set 10 | fort+nelson
Processing Record 44 of Set 10 | santona
Processing Record 45 of Set 10 | bell+ville
Processing Record 46 of Set 10 | da+nang
Processing Record 47 of Set 10 | nome
Processing Record 48 of Set 10 | clarence+town
Processing Record 49 of Set 10 | saint-paul
Processing Record 50 of Set 10 | salta
Processing Record 1 of Set 11 | kurush
Processing Record 2 of Set 11 | poronaysk
Processing Record 3 of Set 11 | kathmandu
Processing Record 4 of Set 11 | kamaishi
Processing Record 5 of Set 11 | qingdao
City not found. Skipping ...
Processing Record 6 of Set 11 | pangkalanbuun
Processing Record 7 of Set 11 | barranca
City not found. Skipping ...
Processing Record 8 of Set 11 | skibbereen
Processing Record 9 of Set 11 | verkhoyansk
Processing Record 10 of Set 11 | verkhnevilyuysk
Processing Record 11 of Set 11 | ikorodu
Processing Record 12 of Set 11 | ukiah
Processing Record 13 of Set 11 | itoman
City not found. Skipping ...
Processing Record 14 of Set 11 | ulyanovsk
Processing Record 15 of Set 11 | clearwater
Processing Record 16 of Set 11 | luganville
Processing Record 17 of Set 11 | durres
Processing Record 18 of Set 11 | ongandjera
Processing Record 19 of Set 11 | port+hardy
Processing Record 20 of Set 11 | ngunguru
City not found. Skipping ...
Processing Record 21 of Set 11 | bogashevo
Processing Record 22 of Set 11 | pareora
Processing Record 23 of Set 11 | havre-saint-pierre
City not found. Skipping ...
Processing Record 24 of Set 11 | norilsk
Processing Record 25 of Set 11 | roxana
Processing Record 26 of Set 11 | kula
Processing Record 27 of Set 11 | hami
Processing Record 28 of Set 11 | todos+santos
Processing Record 29 of Set 11 | majene
City not found. Skipping ...
Processing Record 30 of Set 11 | waipawa
Processing Record 31 of Set 11 | muros
Processing Record 32 of Set 11 | bustamante
Processing Record 33 of Set 11 | pierre
Processing Record 34 of Set 11 | yenagoa
Processing Record 35 of Set 11 | neftcala
Processing Record 36 of Set 11 | washington+terrace
Processing Record 37 of Set 11 | mabaruma
Processing Record 38 of Set 11 | bara
Processing Record 39 of Set 11 | dzhankoy
Processing Record 40 of Set 11 | panjab
Processing Record 41 of Set 11 | maceio
Processing Record 42 of Set 11 | ternate
Processing Record 43 of Set 11 | yerbogachen
Processing Record 44 of Set 11 | ndungu
---------------------------------------------------------------------------
Data Retrieval Complete
---------------------------------------------------------------------------

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

In [11]:
dict = {"City": city_name, "Latitude": lat, "Longitute": lon, "Max Temp (F)": max_temp, "Humidity": humidity, 
       "Cloudiness": cloudiness, "Wind Speed": wind_speed, "Country": country, "Date": date}
cities_df = pd.DataFrame(dict)
cities_df

,City,Latitude,Longitute,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date
0,Mataundh,25.4500,80.1500,87.58,18,10,11.45,IN,1618519896
1,Port Blair,11.6667,92.7500,81.90,74,99,4.76,IN,1618519896
2,Gizo Government Station,-8.1030,156.8419,82.87,75,72,7.11,SB,1618519896
3,Killybegs,54.6333,-8.4500,48.00,73,99,3.00,IE,1618519897
4,Agua Dulce,18.1333,-94.1333,96.80,34,90,2.30,MX,1618519897
...,...,...,...,...,...,...,...,...,...
539,Panjāb,34.3880,67.0233,40.30,66,100,4.65,AF,1618520081
540,Maceió,-9.6658,-35.7353,77.00,94,20,4.61,BR,1618520048
541,Ternate,0.8000,127.4000,80.26,79,100,8.21,ID,1618520081
542,Yerbogachën,61.2767,108.0108,26.51,94,100,16.78,RU,1618520082
543,Ndungu,-4.3667,38.0500,71.37,94,97,1.41,TZ,1618520082

In [12]:
cities_df.to_csv("Output/cities.csv", sep=",", encoding='utf-8',index=False, header=True)

## Inspect the data and remove the cities where the humidity > 100%.
----
Skip this step if there are no cities that have humidity > 100%.

In [65]:
#cities_df["Humidity"] == 70

In [66]:
#test = cities_df[(cities_df["Humidity"] > 80)].index
#test_df = cities_df.drop(test)

In [67]:
#test_df = test_df.reset_index()

In [68]:
#test_df = test_df.set_index("City")

In [69]:
#test_df["Humidity"].plot(kind="bar")
#plt.savefig("Images/test.png")

In [70]:
#Using .loc to build a new dataframe with cities only
supersaturation_df = cities_df.loc[(cities_df["Humidity"] > 100)]
supersaturation_df.count()
#If .count shows 0, no cities in dataframe have humidity values over 100

City            0
Latitude        0
Longitute       0
Max Temp (F)    0
Humidity        0
Cloudiness      0
Wind Speed      0
Country         0
Date            0
dtype: int64

In [71]:
supersaturation_df.head()

Empty DataFrame
Columns: [City, Latitude, Longitute, Max Temp (F), Humidity, Cloudiness, Wind Speed, Country, Date]
Index: []

In [72]:
#  Get the indices of cities that have humidity over 100%.
indices = supersaturation_df.index

In [73]:
# Make a new DataFrame equal to the city data to drop all humidity outliers by index.
# Passing "inplace=False" will make a copy of the city_data DataFrame, which we call "clean_city_data".

In [74]:
cities_df = pd.read_csv(output_data_file)
cities_df

,City,Latitude,Longitute,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date
0,Mataundh,25.4500,80.1500,87.58,18,10,11.45,IN,1618519896
1,Port Blair,11.6667,92.7500,81.90,74,99,4.76,IN,1618519896
2,Gizo Government Station,-8.1030,156.8419,82.87,75,72,7.11,SB,1618519896
3,Killybegs,54.6333,-8.4500,48.00,73,99,3.00,IE,1618519897
4,Agua Dulce,18.1333,-94.1333,96.80,34,90,2.30,MX,1618519897
...,...,...,...,...,...,...,...,...,...
539,Panjāb,34.3880,67.0233,40.30,66,100,4.65,AF,1618520081
540,Maceió,-9.6658,-35.7353,77.00,94,20,4.61,BR,1618520048
541,Ternate,0.8000,127.4000,80.26,79,100,8.21,ID,1618520081
542,Yerbogachën,61.2767,108.0108,26.51,94,100,16.78,RU,1618520082
543,Ndungu,-4.3667,38.0500,71.37,94,97,1.41,TZ,1618520082

In [75]:
cities_df.describe()

,Latitude,Longitute,Max Temp (F),Humidity,Cloudiness,Wind Speed,Date
count,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,5.440000e+02
mean,20.216817,19.020838,58.639118,69.244485,56.058824,8.390239,1.618520e+09
std,33.516784,91.515898,23.822098,22.707950,38.530228,5.731686,8.249440e+01
min,-54.800000,-179.166700,-17.700000,5.000000,0.000000,0.630000,1.618519e+09
25%,-8.032425,-59.583350,44.197500,57.000000,19.750000,4.155000,1.618520e+09
50%,23.541650,18.262800,64.335000,74.000000,72.000000,6.910000,1.618520e+09
75%,48.862450,104.399675,77.670000,87.000000,94.250000,11.462500,1.618520e+09
max,78.218600,179.316700,101.910000,100.000000,100.000000,37.870000,1.618520e+09

## Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

## Latitude vs. Temperature Plot

## Latitude vs. Humidity Plot

## Latitude vs. Cloudiness Plot

## Latitude vs. Wind Speed Plot

## Linear Regression

####  Northern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Southern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Northern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression

####  Southern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression